version: '3.5'
services:
  rabbitmq-container:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  app-producer-container:
    restart: on-failure
    image: producer-rabbitmq
    container_name: app-producer
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq-container
    ports:
      - "8080:8080"
    volumes:
      - /data/producer
